### PR TITLE
feat: [Week View] Option to set the all day events header row title

### PR DESCRIPTION
**Pull request by MartimTSilva**
# Description
Allow user to set a title for the full day row on week view.
New option name: `fullDayHeaderTitle`
image

## Checklist
- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:` etc).
- [x] I have followed the [Contributor Guide] when preparing my PR.
- [ ] I have updated/added tests for ALL new/updated/fixed functionality.
- [ ] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [ ] I have updated/added relevant examples in `examples` or `docs`.

## Breaking Change?

- [ ] Yes, this PR is a breaking change.
- [x] No, this PR is not a breaking change.

## Related Issues
#308 

[Contributor Guide]: https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view/blob/master/CONTRIBUTING.md
[Conventional Commit]: https://conventionalcommits.org

### CODE REVIEW

**Comment by marcmacias96** [comment]
I need this :c

**Comment by MartimTSilva** [comment]
> I need this :c

You can use my forked solution:
https://github.com/MartimTSilva/flutter_calendar_view/tree/feat/allDayHeaderTitle

**Comment by ParthBaraiya** [comment]
Hi @MartimTSilva  Please fix the merge conflicts and update PR.

**Comment by apurva010** [comment]
Create and update this PR in #361.

**Pull request closed without merging**
