### PR TITLE
Issue 311 start hour

### PR DESCRIPTION
**Pull request by rmpt**
Forked from issue [240](https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view/pull/254) that has been dead from some time.

This feature adds a startHour parameter in WeekView + DayView that allows us to choose from which hour a day will be displayed. The parameter is an int that goes from 0 to 23.

Example with the startHour parameter set to 5 :
image

Checklist

The title of my PR starts with a [Conventional Commit](https://conventionalcommits.org/) prefix (fix:, feat:, docs: etc).
I have followed the [Contributor Guide](https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view/blob/master/CONTRIBUTING.md) when preparing my PR.
I have updated/added tests for ALL new/updated/fixed functionality.
I have updated/added relevant documentation in docs and added dartdoc comments with ///.

    I have updated/added relevant examples in examples or docs.

Breaking Change?

Yes, this PR is a breaking change.

    No, this PR is not a breaking change.

Related Issues

Based on the issue https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view/issues/240 but only resolves the 'min' hour.

### CODE REVIEW

**Comment by rmpt** [comment]
can anyone review this PR please?

**Comment by ParthBaraiya** [comment]
Thanks for creating this PR @rmpt . If possible can you please resolve the conflict in one file. I will review this immediately.

**Comment by rmpt** [comment]
@ParthBaraiya please give it a look

**Comment by Adm94** [comment]
@rmpt A good and needed feature thank you 👍🏼 
But I noticed that the live vertical timeline is lowered if startHour is greater than 0 and therefore no longer corresponds to the current time

**Pull request merged**
